app = "devrewoh-portfolio"
primary_region = "sea"  # Seattle - good choice for US West Coast

[build]
dockerfile = "Dockerfile"

[env]
PORT = "8080"
GO_ENV = "production"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

# Health check configuration
[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/health"

# Optional: Custom response headers (your app already handles security headers)
# [[http_service.http_options.response.headers]]
# X-Frame-Options = "DENY"

[vm]
cpu_kind = "shared"
cpus = 1
memory_mb = 256  # Should be plenty for your Go app

# Graceful shutdown handling
[processes]
app = "./devrewoh-portfolio"

# Optional: Configure restart policy
[restart]
policy = "on-failure"